name: Main

on:
  push:
    branches:
      - main
    tags:
      - '**'
    paths-ignore:
      - README.md
      - LICENSE
  pull_request:

jobs:
  Push-Docker:
    name: push-docker
    runs-on: ubuntu-latest-8-cores
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    steps:
      - uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}
      - name: Push container
        run: ./cicd/push_docker.sh
